server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hola_mundo_db}
    username: ${DB_USER:jzuluagaga}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  application:
    name: bolirana-backend
apis:
  odds:
    base-url: ${ODDS_API_BASE_URL:https://api.the-odds-api.com/v4}
    api-key: ${ODDS_API_KEY:}
  thesportsdb:
    base-url: ${THESPORTSDB_BASE_URL:https://www.thesportsdb.com/api/v1/json}
    api-key: ${THESPORTSDB_API_KEY:}
